---
# This playbook deploys the whole application stack in this site.  

- name: apply zabbix agent configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - zabbixagent

#- name: configure and deploy the webservers and application code
#  hosts: webservers
#  remote_user: root
#
#  roles:
#    - web
#
#- name: deploy MySQL and configure the databases
#  hosts: dbservers
#  remote_user: root

#  roles:
#    - db
